name: Atualizar GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate stats
      run: |
        # Add your commands to generate stats here
        echo "Generating stats..."

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add stats.svg langs.svg
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          git commit -m "Atualizando estatísticas do GitHub"
          git push || { echo 'git push failed'; exit 1; }
        fi
